# Generated by Django 3.2.5 on 2021-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysetApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empno', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('pass_date', models.DateField()),
            ],
        ),
    ]
