# Generated by Django 3.2.5 on 2021-08-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bnglrjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Company', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=30)),
                ('Eligibility', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hydjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Company', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=30)),
                ('Eligibility', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mumbaijobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Company', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=30)),
                ('Eligibility', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Punejobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Company', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=30)),
                ('Eligibility', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
    ]
