# Generated by Django 3.2.5 on 2021-10-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inhertianceinModelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='addr',
        ),
    ]
