# Generated by Django 3.2.5 on 2021-09-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Enter a Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Enter an Email')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
