# Generated by Django 3.2.5 on 2021-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relese_date', models.DateField()),
                ('movie_name', models.CharField(max_length=100)),
                ('heo', models.CharField(max_length=100)),
                ('heoine', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
