# Generated by Django 3.2.5 on 2021-09-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='heo',
            new_name='hero',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='heoine',
            new_name='heroine',
        ),
    ]
