# Generated by Django 3.2.5 on 2021-09-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_auto_20210907_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='relese_date',
            field=models.DateTimeField(),
        ),
    ]
