# Generated by Django 3.2.5 on 2021-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyEmployee',
            fields=[
            ],
            options={
                'ordering': ('ename',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxyModelApp.employee',),
        ),
    ]
