# Generated by Django 3.2.5 on 2021-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelBuiltinSignalsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('regi', models.IntegerField(blank=True)),
            ],
        ),
    ]
