# Generated by Django 3.2.5 on 2021-09-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chuck_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('animal', 'ANIMAL'), ('career', 'CAREER'), ('celebrity', 'CELEBRITY'), ('dev', 'DEV'), ('explicit', 'EXPLICIT'), ('fashion', 'FASHION'), ('food', 'FOOD'), ('history', 'HISTORY'), ('money', 'MONEY'), ('movie', 'MOVIE'), ('music', 'MUSIC'), ('political', 'POLITICAL'), ('religion', 'RELIGION'), ('science', 'SCIENCE'), ('sport', 'SPORT'), ('travel', 'TRAVEL')], max_length=10)),
            ],
        ),
    ]
