# Generated by Django 3.2.5 on 2021-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WFMT_JOBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_number', models.CharField(max_length=30)),
                ('sne_id', models.IntegerField()),
                ('scheme_number', models.IntegerField()),
                ('trs_area', models.CharField(max_length=6)),
                ('cp_details', models.CharField(max_length=400)),
            ],
        ),
    ]
