# Generated by Django 3.2.5 on 2021-09-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('taste', models.CharField(max_length=100)),
                ('percentage_of_alchol', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
