# Generated by Django 3.2.5 on 2021-09-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvbeerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='manufacture',
            field=models.CharField(choices=[('inida', 'INDIA'), ('united Kingdom', 'UK'), ('states', 'USA')], default=False, max_length=20),
        ),
    ]
